spring:
  profiles:
    active: ${profile}
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      maxFileSize: 5MB
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

